name: XML-DOM-Lite
version: 0.03
abstract: Lite Pure Perl XML DOM Parser
author: Richard Hundt <richard@protea-systems.com>
license: artistic
distribution_type: module
build_requires:
  Test::More: 0
requires:
  perl: 5.6.1
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.37
